### ISSUE TITLE
No hr style

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-docs-theme#33]
Vanilla has the default hr element styled with a border and margins, but that is not being reflected in docs.vf.io - is this a problem with the docs theme? I think this used to work before…

See docs: https://docs.vanillaframework.io/en/base/typography (scroll to bottom of page)

See Vanilla style: https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_base_hr.scss

Old issue: https://github.com/vanilla-framework/vanilla-framework/issues/710

**Comment by anthonydillon** [comment]
Fixed as part of #39
