### ISSUE TITLE
table of contents: menu sticky if there's enough space

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-docs-theme#7]
_From @nottrobin on December 8, 2016 16:27_

Currently the list will follow you down the page. This means that if the list were longer than the height of your screen (perfectly feasible) there would be no way to ever see the bottom of the list. How should we solve this?

_Copied from original issue: ubuntudesign/docs-vanilla-theme#52_

**Comment by yaili** [comment]
@barrymcgee has this been fixed?

**Comment by nottrobin** [comment]
Since the stickyness relies on JavaScript anyway, it should be pretty feasible for said JavaScript to check if the TOC is too tall for the viewport. So it could only make the menu sticky *if* there's enough space. Thoughts?

**Comment by yaili** [comment]
@nottrobin sounds good to me
